language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.1
  - 7.2

install:
  - composer install

script:
  - composer phpunit
  - composer grumphp

after_success:
  - composer scrutinizer