language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
  - php: 5.6

install:
  - composer install

script:
  - composer grumphp

after_success:
  - bash <(curl -s https://codecov.io/bash) -f build/logs/clover.xml
